Chip documentation/tas 303
qilimanjaro-tech/qililab pull request #553
Opened 2023-10-05 16:09 UTC by visagim

- [ ] changelog

2023-10-17 09:00 UTC, visagim commented
I think I just forgot to push the last changes I had (at the `__init__.py` with most of the explanation for the `chip` module). Let me know if there are any classes with missing documentation

2023-10-20 10:25 UTC, jjmartinezQT requested changes

2023-10-20 10:25 UTC, jjmartinezQT commented on src/qililab/chip/chip.py
>      nodes: list[Node]
This attribute has no definition in the documentation. Could you include it, please?

2023-10-20 10:25 UTC, jjmartinezQT commented on src/qililab/chip/__init__.py
> +The qubit connectivity (chip topology) can be accessed by calling chip.get_topology(), which returns a networkx graph of the qubits Eg.
the abbreviated of 'for example' is written in lower case and separated by dots in between, often with a comma before it to separate it from the rest of the sentence. I would rewrite this like:

"The qubit connectivity (chip topology) can be accessed by calling chip.get_topology(), which returns a networkx graph of the qubits, e.g."

2023-10-20 10:25 UTC, jjmartinezQT commented on src/qililab/chip/node.py
>      alias: str
This attributes are missing definitions in the docs.

2023-10-20 10:25 UTC, jjmartinezQT commented on src/qililab/chip/node.py
>      alias: str
Same with Port class and its attributes, Qubit, Resonator, Coupler and Coil. Also this classes could benefit from better definition of what the class is about.

2023-10-20 15:45 UTC, jjmartinezQT commented on src/qililab/chip/chip.py
>      nodes: list[Node]
Addressed.

2023-10-20 15:46 UTC, jjmartinezQT commented on src/qililab/chip/__init__.py
> +The qubit connectivity (chip topology) can be accessed by calling chip.get_topology(), which returns a networkx graph of the qubits Eg.
done.

2023-10-20 15:46 UTC, jjmartinezQT commented on src/qililab/chip/node.py
>      alias: str
First pass at this done

2023-10-20 15:52 UTC, jjmartinezQT approved these changes

2023-10-20 16:22 UTC, merged