Changing data saving to dataframes and parameters
qilimanjaro-tech/qililab pull request #643
Opened 2023-12-15 18:36 UTC by GuillermoAbadLopez

2024-01-03 20:24 UTC, GuillermoAbadLopez commented
This is how its going:
<img width="852" alt="Screenshot 2024-01-03 at 21 22 05" src="https://github.com/qilimanjaro-tech/qililab/assets/109400222/06ee21e8-5d81-4780-ae67-178b4143e6e6">

2024-01-03 23:55 UTC, GuillermoAbadLopez commented
Improved one:
<img width="1079" alt="Screenshot 2024-01-04 at 00 55 18" src="https://github.com/qilimanjaro-tech/qililab/assets/109400222/ec00991d-ca6e-412a-8c27-0cba3cfc4e4f">

2024-01-04 10:43 UTC, jjmartinezQT requested changes
Can we merge main into this to incorporate latest changes from main, fix the unittest and the code quality before further reviewing? Thanks!

2024-01-04 11:22 UTC, GuillermoAbadLopez commented
> Can we merge main into this to incorporate latest changes from main, fix the unittest and the code quality before further reviewing? Thanks!

Yep definitely, sorry its not passing because I did some changes for everything to work together better! I just put it in InProgress, and I tackle what you said today! 🙌

2024-01-05 09:01 UTC, jjmartinezQT requested changes
This review is still showing the set_parameter changes that are already merged in main no?

2024-01-05 17:33 UTC, GuillermoAbadLopez commented on src/qililab/calibration/calibration_controller.py
> +                        qubits = [int(s) for s in re.findall(r"\d+", "he33llo 42 I'm a 32 string 30")]
Very nice catch haha

2024-01-05 18:06 UTC, GuillermoAbadLopez commented
Last version of the tables:
<img width="1086" alt="Screenshot 2024-01-05 at 19 06 03" src="https://github.com/qilimanjaro-tech/qililab/assets/109400222/bfe1d406-aeab-4866-8670-9e2cf3644022">

2024-01-08 14:03 UTC, jjmartinezQT requested changes
An unittest for calibrate_all is needed, which Isaac is already taking care of. Aside from that, I will test this one running a full autocalibration once the chip is online again in slurm and then we will be able to merge it.

2024-01-09 14:43 UTC, jjmartinezQT approved these changes
This is good to go, amazing job.

2024-01-09 15:40 UTC, merged