[QHC-713] Implement ExperimentExecutor
qilimanjaro-tech/qililab pull request #790
Opened 2024-09-02 15:45 UTC by fedonman

2024-09-03 12:40 UTC, DZPM approved these changes
LGTM

2024-09-05 13:40 UTC, jjmartinezQT requested changes
Silly comment about decimals. This is just amazing, awesome work.

2024-09-05 13:40 UTC, jjmartinezQT commented on src/qililab/qprogram/experiment_executor.py
> +            progress.update(loop_task_id, description=f"Looping over {loop_label}: {variable_value}")
Could we fix the number of decimals here? Fabio got OCD seeing the video, me a little bit less but also. :D

2024-09-05 13:49 UTC, jjmartinezQT approved these changes
Amazing job.

2024-09-05 13:50 UTC, merged