Improving `optimization` word use in the transpilation
qilimanjaro-tech/qililab pull request #862
Opened 2024-12-23 23:49 UTC by GuillermoAbadLopez

2024-12-30 11:07 UTC, GuillermoAbadLopez commented
### The documentation after this PR looks like:
<img width="676" alt="Screenshot 2024-12-30 at 12 05 04" src="https://github.com/user-attachments/assets/09e27b2d-f965-4141-a967-72707cf79335" />
<img width="692" alt="Screenshot 2024-12-30 at 12 05 17" src="https://github.com/user-attachments/assets/ed7b2c10-c50f-465c-826f-fdcffc43be72" />

2025-01-08 15:07 UTC, fedonman requested changes
Nice job! Left some comments.

2025-01-08 15:07 UTC, fedonman commented on src/qililab/digital/circuit_router.py
> +        # Docstring related to the public method: :meth:`.CircuitTranspiler.route_circuit()`. Change it there too.
Is this comment needed here?

2025-01-08 15:07 UTC, fedonman commented on src/qililab/digital/circuit_to_pulses.py
> +        # Docstring related to the public method: :meth:`.CircuitTranspiler.gates_to_pulses()`. Change it there too.
Is this comment needed here?

2025-01-08 15:07 UTC, fedonman commented on src/qililab/digital/circuit_transpiler.py
> +    ) -> tuple[PulseSchedule, dict]:
Add typing details for the returned `dict`, like `dict[str, int]`

2025-01-08 15:07 UTC, fedonman commented on docs/fundamentals/transpilation.rst
> +
Nice!!

2025-01-08 16:19 UTC, GuillermoAbadLopez commented on src/qililab/execute_circuit.py
> +    program: Circuit | list[Circuit], runcard: str | dict, nshots: int = 1, transpile_config: dict = {}
> Also, default parameter values should not be mutable: https://docs.astral.sh/ruff/rules/mutable-argument-default/

Damn, true... I guess I'll have to set it back to `None` then... started like that, but that made the code much uglier, with more checks, that complicated it... 😅. But definitely can go back to it, makes sense 👌

2025-01-08 16:25 UTC, GuillermoAbadLopez commented on src/qililab/execute_circuit.py
> +    program: Circuit | list[Circuit], runcard: str | dict, nshots: int = 1, transpile_config: dict = {}
> I don't like replacing the parameters with a generic dictionary. Now, it is not clear what the dictionary should contain, what are the default values, there is no autocomplete etc.
> 
> In general, having all options as separate parameters is preferred.
> 
> If we really do need to use a single parameter, we should use a NamedDict or a new class.

Yeah I didn't like it either, but it was so many parameters, and might keep growing..., all of them related to the same thing, that in the end discussing it with @visagim we thought, it didn't make sense to keep the params separated 😓 

I also tried first to do a default class, but what I didn;t like about it, is the user having to import and initialize a random class, from a file in `qililab`, dunno how intuitive that would be 😅. But its true that at least you would then have initialization. 

Dunno I'm not 100% convinced what is better, I can try to generate the three examples:
- Keep params separated
- Ganeric kwargs
- Specific qililab dataclass

and ask again in a Code Discussion/daily, where everybody can see it and decide 👍 :

2025-01-08 16:33 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_router.py
> +        # Docstring related to the public method: :meth:`.CircuitTranspiler.route_circuit()`. Change it there too.
Yeah, good point... I actually have a problem here, which I wanted to ask about:

If you see, Inside the `Transpiler` we have basically methods duplicated from the `Optimizer`..., since we removed the handling of multiple circuits at the same time.. One option would be to remove such duplication, but at the same time that duplications serves as a kind of interface to add more functionality, and shows the user which functions can be called from the transpiler directly, so its not super bad...

Of course this makes that the docstrings are duplicated, and *that* is more problematic, since we wouldn't; want our devs, only updating the `Optimizer` docstrings, but not the `Transpiler`'s which are more public. So the options we have are:
- Delete the duplication in some way (I think this will complicate how we show public method to the user...)
- Add this silly comment for devs to notice, that they need to change the public documentation always
- Maybe just delete the docstring from the not public methods? So there is no mistake by the devs? And they know to go and search elsewhere, which docstring to change 🤔...

2025-01-08 16:34 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_router.py
> +        # Docstring related to the public method: :meth:`.CircuitTranspiler.route_circuit()`. Change it there too.
I'll think more about it the next days, and ask the group with a clearer head...

But such problem make me notice there is a structural code problem from base with having this duplication, which maybe should be addressed more deeply... But 😬 ...

2025-01-08 16:35 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_to_pulses.py
> +        # Docstring related to the public method: :meth:`.CircuitTranspiler.gates_to_pulses()`. Change it there too.
Same answer as above, closing this one, to discuss it in the previous one 👌

2025-01-08 16:35 UTC, GuillermoAbadLopez commented on src/qililab/platform/platform.py
> +        transpile_config: dict = {},
Lets discuss it in the above thread, closing this one 👌

2025-01-08 16:36 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_transpiler.py
> +    ) -> tuple[PulseSchedule, dict]:
True, I'll add it 🙌

2025-01-13 08:13 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_router.py
> +        # Docstring related to the public method: :meth:`.CircuitTranspiler.route_circuit()`. Change it there too.
@fedonman, I ended up deciding to delete a bunch of duplicated docstrings, so we don't have confusion on where to update them! 

And deleted the comments you pointed out, instead now I added inside the duplicated docstring itself, check if you agree with the implementation @fedonman 🙌

2025-01-13 12:28 UTC, GuillermoAbadLopez commented on src/qililab/execute_circuit.py
> +    program: Circuit | list[Circuit], runcard: str | dict, nshots: int = 1, transpile_config: dict = {}
## UPDATE:
Okey, i ended up creating a `TypedDict` that can be imported for suggestions/autocompletion 🙌 

Also changed the default value to non-mutable: None 🚀

2025-01-13 14:07 UTC, GuillermoAbadLopez commented
### After the last changes, the documentation for the `execute`'s & `compile` ends up like:
(it only changed the bottom part, the docstring of the `transpile_config` attribute)
<img width="675" alt="Screenshot 2025-01-13 at 15 02 57" src="https://github.com/user-attachments/assets/ac01b780-7b04-47e8-8f2a-a12cbef4a467" />

2025-01-21 13:20 UTC, fedonman requested changes
Great work overall 💯 💯  Left some minor comments.

2025-01-21 13:20 UTC, fedonman commented on src/qililab/digital/circuit_transpiler.py
> +class DigitalTranspileConfig(TypedDict, total=False):
I looked a bit further into this and `TypedDict` is not the way to go. Mainly because the user loses track of the default values. E.g. If I don't provide `routing` is the default True or False? What number is the default `routing_iterations`? I cannot know except if I follow the method callings and find out that the `CircuitTranspiler.transpile_circuit()` uses `routing=False` as default, or `routing_iterations=10`.

Best solution is to make this a `dataclass` with default values, and use the same object in all methods. That means don't do `transpiler.transpile_circuit(program, **(transpile_config or {}))` in line 1182 of Platform, just pass the object: `transpiler.transpile_circuit(program, transpile_config)`

2025-01-21 13:20 UTC, fedonman commented on src/qililab/digital/circuit_transpiler.py
> +class DigitalTranspileConfig(TypedDict, total=False):
Also, could you rename the class to `DigitalTranspilationConfig` and the variable names to `transpilation_config`. Sorry I am a grammar nazi on naming things 😅 It also aligns with the `DigitalCompilationConfig` we already have.

2025-01-21 13:20 UTC, fedonman commented on src/qililab/digital/circuit_transpiler.py
> +            tuple[PulseSchedule, dict[str, int]]: Pulse schedule and final layouts of the qubits, in the circuit {"qI": J}.
Could you explain more what is the returned `dict`? I can't understand the `{"qI": J}` example.

2025-01-22 09:49 UTC, GuillermoAbadLopez commented on docs/fundamentals/transpilation.rst
> +    \*\*) If ``optimize=False`` in ``transpile_config`` (default behavior), steps 2. and 5. are skipped.
Okey, yes I understand this might not be the best, lemme change it!

2025-01-22 09:51 UTC, GuillermoAbadLopez commented on docs/fundamentals/transpilation.rst
> +    \*\*) If ``optimize=False`` in ``transpile_config`` (default behavior), steps 2. and 5. are skipped.
Changed all of them, and I think now they are much better, let me know what you think 👍 

<img width="309" alt="Screenshot 2025-01-22 at 10 45 50" src="https://github.com/user-attachments/assets/12798262-b160-4930-af3d-c5e52e2ec55e" />
<img width="348" alt="Screenshot 2025-01-22 at 10 45 30" src="https://github.com/user-attachments/assets/3ec8fa2b-644c-4cf8-bb12-d33efbe6cf41" />
<img width="328" alt="Screenshot 2025-01-22 at 10 45 41" src="https://github.com/user-attachments/assets/10a3d0a3-b7ba-43ff-9874-6b1a80626588" />
<img width="328" alt="Screenshot 2025-01-22 at 10 45 41" src="https://github.com/user-attachments/assets/a4325b33-2e76-4df1-9950-e1299ad73dbd" />
<img width="381" alt="Screenshot 2025-01-22 at 10 48 44" src="https://github.com/user-attachments/assets/67ccc822-6eaa-41d8-bc86-45b592a7325a" />

2025-01-22 10:40 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_to_pulses.py
> +    def run(self, gate_list: list[gates.Gate]) -> PulseSchedule:
Right, seems reasonable, I'll change it, but I'll call it `circ_gates` instead, cause gates is an import from qibo, and also this way the name has even more info 👌

2025-01-22 10:43 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_transpiler.py
> +            tuple[PulseSchedule, dict[str, int]]: Pulse schedule and final layouts of the qubits, in the circuit {"qI": J}.
Yeah. actually i have a full [other PR for this](https://github.com/qilimanjaro-tech/qililab/pull/869) (the next one I'm gonna tackle)

Do you mind if we leave it like this for now, and I address it immediately there? We can even wait until all PRs are approved separately, and merge them together into `main`, so there is no moment, were this is public 👌

2025-01-22 10:54 UTC, fedonman commented on src/qililab/digital/circuit_to_pulses.py
> +    def run(self, gate_list: list[gates.Gate]) -> PulseSchedule:
`circ_gates` is an abbreviation though, that we don't want either. `circuit_gates` is the full name.

2025-01-22 10:56 UTC, fedonman commented on src/qililab/digital/circuit_to_pulses.py
> +    def run(self, gate_list: list[gates.Gate]) -> PulseSchedule:
However, the logic goes like this: Your own library is more important than the imported library. So if you want to use `gates` and Qibo is already using `gates`, you just rename Qibo's to something else e.g. `from qibo import gates as qibo_gates`. Or use the full path: `import  qibo` and then `qibo.gates.X`.

2025-01-22 11:02 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_to_pulses.py
> +    def run(self, gate_list: list[gates.Gate]) -> PulseSchedule:
> However, the logic goes like this: Your own library is more important than the imported library. So if you want to use gates and Qibo is already using gates, you just rename Qibo's to something else e.g. from qibo import gates as qibo_gates. Or use the full path: import  qibo and then qibo.gates.X.

Yeah, I actually was gonna do that first, but then I thought that in this case it might be better to have `circ_gates` actually, since all these are lists of gates from the same circuit! So I think it really is more useful here 👌 

I'll change the abbreviation to the full `circuit_gates` 🔥

2025-01-22 11:47 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_to_pulses.py
> +    def run(self, gate_list: list[gates.Gate]) -> PulseSchedule:
Changed!

2025-01-22 11:48 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_to_pulses.py
> +    def run(self, gate_list: list[gates.Gate]) -> PulseSchedule:
Also did [this other PR,](https://github.com/qilimanjaro-tech/qililab/pull/881) to `main` changing some extra ones I found, not related to this PR 👌

2025-01-22 11:56 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_transpiler.py
> +class DigitalTranspileConfig(TypedDict, total=False):
hahaa dun't worry, I think that a great idea for all the company overall TOC :) 🙌

2025-01-22 14:28 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_transpiler.py
> +class DigitalTranspileConfig(TypedDict, total=False):
Done! 🔥

2025-01-22 14:28 UTC, GuillermoAbadLopez commented on src/qililab/digital/circuit_transpiler.py
> +class DigitalTranspileConfig(TypedDict, total=False):
just changed to what you said 👍

2025-02-04 12:19 UTC, fedonman approved these changes
Great work! 💯 💯 💯 

![nodding-yes](https://github.com/user-attachments/assets/f8d4bea9-9c35-476f-8439-ed087613abdd)

2025-02-07 14:53 UTC, fedonman commented
@GuillermoAbadLopez Please refrain from adding new commits to a PR once it is approved, because it needs re-approving and is difficult to see which changes are made. Always create a new PR for these cases! 🙏

2025-02-07 15:16 UTC, GuillermoAbadLopez commented
Also I will need to add some more changes, since there is a problem with the ordering of the returned results.

it will be more complicated than I though, due to multiple measurements, and measurements not needed to be in the end of a circuit... (But I'll create a new PR pointing here for that 👍 )

2025-02-10 11:24 UTC, fedonman commented
@GuillermoAbadLopez Merge this PR, so other PRs point to main please 🙏

2025-02-10 17:24 UTC, GuillermoAbadLopez commented
@fedonman can't do it like that, since the commits are already in this branch! 

We would need to:
1) review that PR, before mergin this to `main`
2) Merge the other one, which contains the commits approved alerady, but then that would mess the information/historial the PRs have...
3) Undo the commits here, and merge this one, and create a new one with the new commits... which is what would be more serious, but what would take more time..

I would rather do 1) if we can, we will lose much less time, and I don't think those changes are sucha. big deal, to make us lose time over them

2025-02-12 08:56 UTC, GuillermoAbadLopez commented
Also. these changes actually were necessary to be in this PR i believe, since they arise from testing this one in HW, without them this code would be buggy, so I don't think it's a good idea to merge it, and have another PR to solve it, if we can solve it before putting in `main` 👌  (of course I could have done a PR that pointed here, but i didn't 😅 )

So now that we have a first thing that works with these last changes, I won't expand this branch any further (we merge it), I'll create new PR for next improvements 👍

2025-02-12 08:56 UTC, GuillermoAbadLopez commented
Also @fedonman . these changes actually were necessary to be in this PR i believe, since they arise from testing this one in HW, without them this code would be buggy, so I don't think it's a good idea to merge it, and have another PR to solve it, if we can solve it before putting in main 👌 (of course I could have done a PR that pointed here, but i didn't 😅 )

So now that we have a first thing that works with these last changes, I won't expand this branch any further (we merge it), I'll create new PR for next improvements 👍

2025-02-17 14:05 UTC, merged